### PR TITLE
Update for GHC >= 9.4

### PR DESCRIPTION
**Pull request by treeowl**
* GHC 9.4 finally gives us the levity-polymorphic primops we need to make this package work reliably and legitimately. For these GHC versions, do so, and get rid of now-unnecessary `NOINLINE`s.

* Adjust language pragmas to avoid new warnings.

### CODE REVIEW

**Comment by treeowl** [comment]
Some things remain a bit unsatisfying. We still have our own newtypes around the primitive types, and more annoyingly, those are exported abstractly! We can't expose the constructors nicely for just new GHC versions without an API mess. We can't drop the newtypes and just use the primitive ones without potentially breaking stuff for users. Ugh.

**Comment by andrewthad** [comment]
> We can't drop the newtypes and just use the primitive ones without potentially breaking stuff for users.

Do you mean that you are concerned about backwards compatibility or something else? I don't think that backwards compatibility needs to be a concern at all.

**Comment by treeowl** [comment]
I think probably the Right Thing is to merge this, make a minor release, and then make a major release to switch over to the bare GHC way.

**Comment by treeowl** [comment]
Actually, this could probably even be a patch-level release, right? Would you be up for it, @andrewthad ?

**Pull request merged**
